### ISSUE TITLE
Epic: DiffViewer Plus Improvements

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#591]
Review and merge changes from fork https://github.com/til77/scenarioo

Pull Request for reviewing:
https://github.com/scenarioo/scenarioo/pull/593

Let's collect the issues that should be addressed here in this epic:

* [x] #601 - ordering of branches in branch selection list.
* [x] #596 - default highlight color for diff screenshots configurable
* [x] #577 - no confusing null pointer exceptions that should not be there (assumed to be fixed)
* [x] #602 - Remove GraphicMagick Dependency
* [x] #618 - new internal diff viewer format (less disk space, attached to belonging build)
* [x] #603 - Review and adjust Step Comparison View

further issues - done later ... (see Milestone https://github.com/scenarioo/scenarioo/milestone/33 )
* [ ] #605 - Change and document new REST API for diff calculation
* [ ] #600 - avoid server blocked from startup if there are build data inconsistencies (to be verified!).
* [ ] #598 - avoid further problems with outdated libraries in java 8
* [ ] #604 - improve background comparison calculation (use power of multi threading)

Out Of Scope (no time):
* #573 - no disabled comparison in URL
* #568 - responsive layout of labels in step comparison view for small screens
* #599 - advanced views to see change rate for each page as well and all screens of one page.

**Comment by kabl** [comment]
In Review:
- #601 - ordering of branches in branch selection list.
- #596 - default highlight color for diff screenshots configurable

**Comment by bruderol** [comment]
I will close this, see remaining issues for what happens to them.

All reamining work for the realse is here on the milestone and will be tracked there:
https://github.com/scenarioo/scenarioo/milestone/33
